### ISSUE TITLE
Convert a PRR YAML checklist to a Material-UI table.

### ISSUE THREAD

**Issue by Alex-Potter-Dixon** [glasswall-sre/glasswall-sre.github.io#1]
A PRR is a CSV file and on the documentation site, we should present the PRR under the product page. 

Need to create a React component to read the CSV, parse it and create a table https://material-ui.com/components/tables/. 

- [ ] Table should have the following columns:
Action
Completed
Date
Sign off
Evidence 

- [ ] Each evidence row should have a button to open a modal that shows the full text. 
- [ ] Easy to read visual icons for completed
